# (PART) Introduction to Predictive Analytics {#part-introduction-to-predictive-analytics .unnumbered}

# Overview of Predictive Analytics {#overview-of-predictive-analytics}

## Introduction {.unnumbered}

This foundational chapter streamlines the material scattered in different parts
of the PA e-learning modules and provides a broad and coherent introduction to
predictive analytics.

Setting the scene for pretty much everything that comes later, it walks you
through the main steps in building a predictive model and presents the
fundamental concepts in predictive analytics that you will see repeatedly in the
rest of this manual.

These concepts are universally applicable in the sense that they apply to
essentially all types of predictive model, and will be illustrated in the
context of specific types of model (GLMs and decision trees, in particular) in
later chapters.

--------------------------------------------------------------------------------

## Basic Terminology {#basic-terminology}

**Predictive Analytics in a nutshell.** Three main categories of predictive
analytics problems:

-   ***Descriptive:*** Focuses on what happened in the past and aims to
    "describe" or explain the observed patterns by identifying the relationships
    between different variables in the data.

    **Example.** If you saw an increase in the lapse rate among the
    policyholders of a certain line of business, what kind of policyholders had
    the highest tendency to lapse? What are their key characteristics? This is a
    question addressed by descriptive analytics.

-   ***Predictive:*** Focuses on what will happen in the *future* and is
    concerned with making accurate "predictions".

    **Example:** For a prospective policyholder with certain characteristics,
    what is their predicted probability of lapse? The ability to make such a
    prediction will be useful for identifying future policyholders who will have
    a lower probability of lapse and contribute to the profitability of an
    insurer.

-   ***Prescriptive:*** Uses a combination of optimization and simulation to
    quantify the impact of different "prescribed" actions in different
    scenarios.

    **Example:** If we reduce the premium by a certain amount, how will this
    affect the lapse rate? More generally, what is the best course of action to
    reduce the lapse rate? Prescriptive analytics may give us some useful
    insight.

All predictive problems have something in common. There is always an output (or
outcome) of interest, which can be numeric (salary, premium) or categorical
(positive/negative, email/spam), and we have at our disposal a collection of
input variables that may offer potentially useful information for predicting or
understanding the output.

This "input-output" setting, depicted below, is characteristic of predictive
analytics in general, and our job is to develop a model teasing the (possibly
complex, overlapping) contributions of the inputs to the output.

$$
\underset{\underset{Output}{\text{Target Variable}}}{Y} \overset{\text{Predict}}{\underset{\text{}}{\dashleftarrow}}\underset{\underset{Inputs}{\text{Predictors}}}{X = (X_1,...,Xp)}
$$

--------------------------------------------------------------------------------

**Classification of Variables.** Predictive analytics requires data, often with
a large number of observations and variables. In Exam PA, we will be mostly
dealing with datasets that can be displayed in the following
observation-by-variable rectangular array format (such data is called
***structured data*** and is stored in `R` in a data frame).

| ***Observation*** | ***Target*** | ***Predictors*** |          |       |          |
|:-----------------:|:------------:|:----------------:|:--------:|:-----:|:--------:|
|                   |     $Y$      |      $X_1$       |  $X_2$   | $...$ |  $X_p$   |
|        $1$        |    $Y_1$     |     $X_{11}$     | $X_{12}$ | $...$ | $X_{1p}$ |
|        $2$        |    $Y_2$     |     $X_{21}$     | $X_{22}$ | $...$ | $X_{2p}$ |
|       $...$       |    $...$     |      $...$       |  $...$   | $...$ |  $...$   |
|        $n$        |    $Y_n$     |     $X_{n1}$     | $X_{n2}$ | $...$ | $X_{np}$ |

: **TABLE 1:** Structured Data Format

In the dataset above, the *observations* are shown across the rows of the array
(from 1 to $n$) and the corresponding *variable* values are shown in the
columns. Each observation comprises measurements taken for multiple variables,
so, for example, the first observation of the data consists of:

$$
Y_1,X_{11},X_{12},...,X_{1p},
$$

not just $Y_1$ or $X_{11},X_{12},...,X_{1p}$. In the actuarial salary example
above, you can think of each observation as an actuary you are able to sample,
and the variables represent the characteristics of that actuary.

Generally speaking, there are two ways to classify variables in a predictive
analytics context: By their role in the study (intended use) or by their nature
(characteristics).

-   **By Role: Target vs. Predictors**

    In the dataset above, we refer to the variable that we are interested in as
    the ***target variable***, or simply the ***target*** (a.k.a ***response
    variable***, ***dependent variable***, ***output variable**, **outcome
    variable**),* and denote it by $\bf{Y}$.

    Despite the target variable being our prime interest, in most situations we
    cannot change the target directly, but we have more direct control over some
    associated variables which may offer explanatory information about the
    target. These variables go by different names, such as ***predictors***,
    ***explanatory variables, independent variables, input variables,*** or
    sometimes simply ***variables*** if no confusion arises, and we denote them
    by $\bf{X_1, X_2, ..., X_p}$. In an actuarial context, predictors are also
    known as risk factors or risk drivers. In the rest of this manual, we will
    mostly use the term "predictors" and "features".

    Throughout the study of predictive analytics, it is useful to think of a
    predictive model as the following functional relationship between the target
    variable $\bf{Y}$ and the corresponding set of $\bf{p}$ predictors
    $\bf{X=(X_1,...,X_p)}$ (collected as a vector):

    $$
    \begin{equation}
    Y_i=f\left(X_i\right)+\epsilon_i, i=1,...,n
    (\#eq:modelformula)
    \end{equation}
    $$

    where:

    -   The subscript $i$ signifies the $i$-th observation in the dataset, so
        $Y_i$ is the value of the target variable for the $i$-th observation and
        $X_i = (X_{i1}, ..., X_{ip})$ is the corresponding vector of predictor
        values.
    -   $f$ is a fixed (non-random) but unknown function corresponding the
        predictors and the target variable.
        -   Without the subscript $i$ (note that is $f$ rather than $f_i$), the
            function applies to all observations in the data, and forms the
            "systematic" part of \@ref(eq:modelformula).
        -   Largely synonymous with the model, this function carries the
            systematic information that the predictors offer about the target
            variable, and allows us to differentiate, or discriminate, the
            observations of the target variable on the basis of those
            predictors.
    -   $\epsilon_i$ is a zero-mean random error term carrying information that
        is specific to the $i$-th observation, hence "idiosyncratic" and the
        presence of the subscript $i$.
        -   It can be regarded as the catch-all for what the systematic
            component of the model misses, e.g., the true relationship between
            $X$ and $Y$ is probably more complex than \@ref(eq:modelformula),
            there are other variables associated with $Y$ omitted by the model.

    Although \@ref(eq:modelformula) looks abstract and the exam will not test it
    directly, it will provide a useful framework for thinking about predictive
    analytics. For convenience, we will refer to $f$ and $\epsilon_i$
    respectively as the signal function and the noise, which are widely used
    terms originally stemming from engineering.

    Goal of Predictive Analytics

    :   We are interested in the signal, but the data we have is "contaminated"
        with noise.

        The goal of predictive analytics is to filter out the noise and use a
        variety of tools and techniques to learn as much and as accurately about
        the signal as possible from the data.

        The knowledge about the signal can then provide us with a basis for
        understanding the data-generating process underlying the population of
        interest and making predictions for the target variable.

-   **By Nature: Numeric vs. Categorical**

    Variables can also be classified as ***numeric*** variables or
    ***categorical*** variables. Such a classification has important
    implications for developing an effective predictive model that aligns with
    the characteristics of the target variable and predictors to produce
    realistic output.

    -   **Numeric (Quantitative) Variables:** Numeric values that can take the
        form of numbers with a well-defined order and an associated range.
        -   **Discrete:** Restricted to only certain numeric values in that
            range, e.g., non-negative numbers.
        -   **Continuous:** Can assume any numeric value within the range of the
            variable, at least in theory.
    -   **Categorical (Qualitative/Factor) Variables:** Takes predefined values
        in a countable collection of "categories", also called the ***levels***
        or ***classes*** of the variable.
        -   **Nominal:**Levels have no numeric order, i.e., we cannot say which
            category is larger or smaller.
            -   **Examples:** Smoking Status, Gender, Marital Status
        -   **Ordinal:** Levels have a natural order.
            -   **Examples:** Health Status (Poor, Moderate, Good), Risk Group
                (Preferred, Standard, Rated, Uninsurable).

    ```{block2, type='rmdnote'}
    In predictive modeling, the type of model to use is largely determined by the the nature of the target variable, not the predictors.

    In other words, the distinction between numeric and categorical variables is relatively unimportant when they serve as predictors of a model, but we do need to take the distinction properly into account when they serve as the target variable.

    Some predictive models (e.g., linear models) work well only for numeric target variables while some (e.g., GLMs and decision trees) apply to both numeric and categorical target variables.
    ```

--------------------------------------------------------------------------------

**Supervised vs. Unsupervised Problems.** Given the notions of target vs.
predictor variables and numeric vs. categorical variables, we can further
classify predictive analytics problems. Depending on the presence of a target
variable and the objective of analysis, we can describe them as ***supervised***
or ***unsupervised learning***.

-   **Supervised Learning:** Refers to those for which there is a target
    variable "supervising" or guiding the analysis, and our goal is to
    understand the relationship between the target and the predictors, and/or
    make accurate predictions for the target based on the predictors.
    -   <div>

        | **Models:** GLMs (including linear models) and Decision Trees

        </div>
-   **Unsupervised Learning:** For unsupervised learning methods, there is no
    target variable supervising our analysis, and we are interested in
    extracting relationships and structures between different variables in the
    data.
    -   <div>

        | **Models:** Principal Components Analysis (PCA) and Cluster Analysis

        </div>

--------------------------------------------------------------------------------

**Regression vs. Classification Problems.** Finally, it is customary to refer to
supervised learning problems with a numeric target variable as ***regression
problems*** (an exception is logistic regression, for which the target variable
is binary). In contrast, when the target variable is categorical in nature, we
are dealing with ***classification problems***. A predictive model for
predicting a categorical target involves "classifying" its observations to a
certain level and is aptly called a *classifier*.

Both regression and classification problems are of importance in Exam PA and
predictive modeling in general. The two kinds of predictive analytics problems
have their unique features and will be covered in detail in Part II of this
manual.

--------------------------------------------------------------------------------

## The Model Building Process {#the-model-building-process}

## Bias-Variance Trade-off {#bias-variance-trade-off}

## Feature Generation and Selection {#feature-generation-and-selection}

## Conceptual Review Questions for Chapter 1 {#conceptual-review-questions-for-chapter-1}
